services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: racunari_backend
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      S3_BUCKET: ${S3_BUCKET}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: racunari_frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - backend

networks:
  app_network:
    driver: bridge
